---
- hosts: all
  tasks:
  - name: Upgrade all packages to the latest version
    become: true
    apt:
      name: "*"
      state: latest

  - name: Update all packages to the latest version
    become: true
    apt:
      upgrade: dist